// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sobel_sqrt_fixed_32_32_s (
        ap_clk,
        ap_rst,
        x,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] x;
output  [15:0] ap_return;
input   ap_ce;

reg[15:0] ap_return;

reg   [31:0] x_read_reg_1523;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] x_read_reg_1523_pp0_iter1_reg;
reg   [31:0] x_read_reg_1523_pp0_iter2_reg;
wire   [0:0] icmp_ln443_fu_232_p2;
reg   [0:0] icmp_ln443_reg_1529;
wire   [2:0] add_ln212_fu_242_p2;
reg   [2:0] add_ln212_reg_1535;
wire   [34:0] x_l_I_V_36_fu_670_p3;
reg   [34:0] x_l_I_V_36_reg_1540;
wire   [15:0] res_I_V_37_fu_678_p3;
reg   [15:0] res_I_V_37_reg_1546;
wire   [0:0] icmp_ln443_6_fu_718_p2;
reg   [0:0] icmp_ln443_6_reg_1552;
wire   [8:0] sub_ln212_5_fu_724_p2;
reg   [8:0] sub_ln212_5_reg_1558;
wire   [34:0] x_l_I_V_41_fu_1155_p3;
reg   [34:0] x_l_I_V_41_reg_1563;
wire   [15:0] res_I_V_42_fu_1163_p3;
reg   [15:0] res_I_V_42_reg_1569;
reg   [12:0] p_Result_34_reg_1575;
reg   [14:0] p_Result_84_reg_1580;
wire    ap_block_pp0_stage0;
wire   [1:0] tmp_fu_222_p4;
wire   [2:0] zext_ln212_fu_238_p1;
wire   [34:0] zext_ln666_fu_248_p1;
wire   [34:0] p_Result_50_fu_251_p5;
wire   [15:0] res_I_V_32_fu_269_p3;
wire   [1:0] p_Result_s_66_fu_276_p4;
wire   [34:0] x_l_I_V_31_fu_262_p3;
wire   [2:0] tmp_1_fu_286_p3;
wire   [3:0] p_Result_51_fu_294_p4;
wire   [3:0] zext_ln443_fu_304_p1;
wire   [3:0] sub_ln212_fu_314_p2;
wire   [0:0] icmp_ln443_1_fu_308_p2;
wire   [34:0] p_Result_52_fu_320_p5;
wire   [15:0] p_Result_53_fu_332_p4;
wire   [15:0] res_I_V_33_fu_350_p3;
wire   [2:0] p_Result_4_fu_358_p4;
wire   [34:0] x_l_I_V_32_fu_342_p3;
wire   [3:0] tmp_2_fu_368_p3;
wire   [4:0] p_Result_54_fu_376_p4;
wire   [4:0] zext_ln443_1_fu_386_p1;
wire   [4:0] sub_ln212_1_fu_396_p2;
wire   [0:0] icmp_ln443_2_fu_390_p2;
wire   [34:0] p_Result_55_fu_402_p5;
wire   [15:0] p_Result_56_fu_414_p4;
wire   [15:0] res_I_V_34_fu_432_p3;
wire   [3:0] p_Result_8_fu_440_p4;
wire   [34:0] x_l_I_V_33_fu_424_p3;
wire   [4:0] tmp_3_fu_450_p3;
wire   [5:0] p_Result_57_fu_458_p4;
wire   [5:0] zext_ln443_2_fu_468_p1;
wire   [5:0] sub_ln212_2_fu_478_p2;
wire   [0:0] icmp_ln443_3_fu_472_p2;
wire   [34:0] p_Result_58_fu_484_p5;
wire   [15:0] p_Result_59_fu_496_p4;
wire   [15:0] res_I_V_35_fu_514_p3;
wire   [4:0] p_Result_10_fu_522_p4;
wire   [34:0] x_l_I_V_34_fu_506_p3;
wire   [5:0] tmp_4_fu_532_p3;
wire   [6:0] p_Result_60_fu_540_p4;
wire   [6:0] zext_ln443_3_fu_550_p1;
wire   [6:0] sub_ln212_3_fu_560_p2;
wire   [0:0] icmp_ln443_4_fu_554_p2;
wire   [34:0] p_Result_61_fu_566_p5;
wire   [15:0] p_Result_62_fu_578_p4;
wire   [15:0] res_I_V_36_fu_596_p3;
wire   [5:0] p_Result_13_fu_604_p4;
wire   [34:0] x_l_I_V_35_fu_588_p3;
wire   [6:0] tmp_5_fu_614_p3;
wire   [7:0] p_Result_63_fu_622_p4;
wire   [7:0] zext_ln443_4_fu_632_p1;
wire   [7:0] sub_ln212_4_fu_642_p2;
wire   [0:0] icmp_ln443_5_fu_636_p2;
wire   [34:0] p_Result_64_fu_648_p5;
wire   [15:0] p_Result_65_fu_660_p4;
wire   [6:0] p_Result_16_fu_686_p4;
wire   [7:0] tmp_6_fu_696_p3;
wire   [8:0] p_Result_66_fu_704_p4;
wire   [8:0] zext_ln443_5_fu_714_p1;
wire   [34:0] p_Result_67_fu_730_p5;
wire   [15:0] p_Result_68_fu_740_p4;
wire   [15:0] res_I_V_38_fu_755_p3;
wire   [7:0] p_Result_19_fu_761_p4;
wire   [34:0] x_l_I_V_fu_749_p3;
wire   [8:0] tmp_7_fu_771_p3;
wire   [9:0] p_Result_69_fu_779_p4;
wire   [9:0] zext_ln443_6_fu_789_p1;
wire   [9:0] sub_ln212_6_fu_799_p2;
wire   [0:0] icmp_ln443_7_fu_793_p2;
wire   [34:0] p_Result_70_fu_805_p5;
wire   [15:0] p_Result_71_fu_817_p4;
wire   [15:0] res_I_V_fu_835_p3;
wire   [8:0] p_Result_22_fu_843_p4;
wire   [34:0] x_l_I_V_37_fu_827_p3;
wire   [9:0] tmp_8_fu_853_p3;
wire   [10:0] p_Result_72_fu_861_p4;
wire   [10:0] zext_ln443_7_fu_871_p1;
wire   [10:0] sub_ln212_7_fu_881_p2;
wire   [0:0] icmp_ln443_8_fu_875_p2;
wire   [34:0] p_Result_73_fu_887_p5;
wire   [15:0] p_Result_74_fu_899_p4;
wire   [15:0] res_I_V_39_fu_917_p3;
wire   [9:0] p_Result_25_fu_925_p4;
wire   [34:0] x_l_I_V_38_fu_909_p3;
wire   [10:0] tmp_9_fu_935_p3;
wire   [11:0] p_Result_75_fu_943_p4;
wire   [11:0] zext_ln443_8_fu_953_p1;
wire   [11:0] sub_ln212_8_fu_963_p2;
wire   [0:0] icmp_ln443_9_fu_957_p2;
wire   [34:0] p_Result_76_fu_969_p5;
wire   [15:0] p_Result_77_fu_981_p4;
wire   [15:0] res_I_V_40_fu_999_p3;
wire   [10:0] p_Result_28_fu_1007_p4;
wire   [34:0] x_l_I_V_39_fu_991_p3;
wire   [11:0] tmp_s_fu_1017_p3;
wire   [12:0] p_Result_78_fu_1025_p4;
wire   [12:0] zext_ln443_9_fu_1035_p1;
wire   [12:0] sub_ln212_9_fu_1045_p2;
wire   [0:0] icmp_ln443_10_fu_1039_p2;
wire   [34:0] p_Result_79_fu_1051_p5;
wire   [15:0] p_Result_80_fu_1063_p4;
wire   [15:0] res_I_V_41_fu_1081_p3;
wire   [11:0] p_Result_31_fu_1089_p4;
wire   [34:0] x_l_I_V_40_fu_1073_p3;
wire   [12:0] tmp_10_fu_1099_p3;
wire   [13:0] p_Result_81_fu_1107_p4;
wire   [13:0] zext_ln443_10_fu_1117_p1;
wire   [13:0] sub_ln212_10_fu_1127_p2;
wire   [0:0] icmp_ln443_11_fu_1121_p2;
wire   [34:0] p_Result_82_fu_1133_p5;
wire   [15:0] p_Result_83_fu_1145_p4;
wire   [13:0] tmp_11_fu_1198_p3;
wire   [14:0] zext_ln443_11_fu_1205_p1;
wire   [14:0] sub_ln212_11_fu_1214_p2;
wire   [0:0] icmp_ln443_12_fu_1209_p2;
wire   [34:0] p_Result_85_fu_1219_p5;
wire   [15:0] p_Result_86_fu_1230_p4;
wire   [15:0] res_I_V_43_fu_1246_p3;
wire   [13:0] p_Result_37_fu_1253_p4;
wire   [34:0] x_l_I_V_42_fu_1239_p3;
wire   [14:0] tmp_12_fu_1263_p3;
wire   [15:0] p_Result_87_fu_1271_p4;
wire   [15:0] zext_ln443_12_fu_1281_p1;
wire   [15:0] sub_ln212_12_fu_1291_p2;
wire   [0:0] icmp_ln443_13_fu_1285_p2;
wire   [34:0] p_Result_88_fu_1297_p5;
wire   [15:0] p_Result_89_fu_1309_p4;
wire   [15:0] res_I_V_44_fu_1327_p3;
wire   [14:0] p_Result_40_fu_1335_p4;
wire   [34:0] x_l_I_V_43_fu_1319_p3;
wire   [15:0] tmp_13_fu_1345_p3;
wire   [16:0] p_Result_90_fu_1353_p4;
wire   [16:0] zext_ln443_13_fu_1363_p1;
wire   [16:0] sub_ln212_13_fu_1373_p2;
wire   [0:0] icmp_ln443_14_fu_1367_p2;
wire   [34:0] p_Result_91_fu_1379_p5;
wire   [15:0] p_Result_92_fu_1391_p4;
wire   [15:0] res_I_V_45_fu_1409_p3;
wire   [34:0] x_l_I_V_44_fu_1401_p3;
wire   [16:0] tmp_14_fu_1417_p3;
wire   [17:0] p_Result_93_fu_1425_p1;
wire   [17:0] zext_ln443_14_fu_1429_p1;
wire   [17:0] sub_ln212_14_fu_1439_p2;
wire   [0:0] icmp_ln443_15_fu_1433_p2;
wire   [34:0] p_Result_94_fu_1445_p5;
wire   [15:0] p_Result_95_fu_1457_p4;
wire   [15:0] res_I_V_46_fu_1475_p3;
wire   [32:0] mul_I_V_fu_1483_p3;
wire   [34:0] x_l_I_V_45_fu_1467_p3;
wire   [34:0] zext_ln671_fu_1491_p1;
wire   [0:0] p_Result_48_fu_1495_p2;
wire   [15:0] res_I_V_30_fu_1501_p2;
wire   [0:0] p_Result_s_fu_1191_p3;
wire   [15:0] res_I_V_47_fu_1507_p3;
wire   [15:0] select_ln53_fu_1515_p3;
reg    ap_ce_reg;
reg   [31:0] x_int_reg;
reg   [15:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln212_reg_1535 <= add_ln212_fu_242_p2;
        icmp_ln443_6_reg_1552 <= icmp_ln443_6_fu_718_p2;
        icmp_ln443_reg_1529 <= icmp_ln443_fu_232_p2;
        p_Result_34_reg_1575 <= {{res_I_V_42_fu_1163_p3[15:3]}};
        p_Result_84_reg_1580 <= {{x_l_I_V_41_fu_1155_p3[20:6]}};
        res_I_V_37_reg_1546 <= res_I_V_37_fu_678_p3;
        res_I_V_42_reg_1569 <= res_I_V_42_fu_1163_p3;
        sub_ln212_5_reg_1558 <= sub_ln212_5_fu_724_p2;
        x_l_I_V_36_reg_1540 <= x_l_I_V_36_fu_670_p3;
        x_l_I_V_41_reg_1563 <= x_l_I_V_41_fu_1155_p3;
        x_read_reg_1523 <= x_int_reg;
        x_read_reg_1523_pp0_iter1_reg <= x_read_reg_1523;
        x_read_reg_1523_pp0_iter2_reg <= x_read_reg_1523_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln53_fu_1515_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_int_reg <= x;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln53_fu_1515_p3;
    end else begin
        ap_return = 'bx;
    end
end

assign add_ln212_fu_242_p2 = ($signed(zext_ln212_fu_238_p1) + $signed(3'd7));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign icmp_ln443_10_fu_1039_p2 = ((p_Result_78_fu_1025_p4 < zext_ln443_9_fu_1035_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_11_fu_1121_p2 = ((p_Result_81_fu_1107_p4 < zext_ln443_10_fu_1117_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_12_fu_1209_p2 = ((p_Result_84_reg_1580 < zext_ln443_11_fu_1205_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_13_fu_1285_p2 = ((p_Result_87_fu_1271_p4 < zext_ln443_12_fu_1281_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_14_fu_1367_p2 = ((p_Result_90_fu_1353_p4 < zext_ln443_13_fu_1363_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_15_fu_1433_p2 = ((p_Result_93_fu_1425_p1 < zext_ln443_14_fu_1429_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_1_fu_308_p2 = ((p_Result_51_fu_294_p4 < zext_ln443_fu_304_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_2_fu_390_p2 = ((p_Result_54_fu_376_p4 < zext_ln443_1_fu_386_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_3_fu_472_p2 = ((p_Result_57_fu_458_p4 < zext_ln443_2_fu_468_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_4_fu_554_p2 = ((p_Result_60_fu_540_p4 < zext_ln443_3_fu_550_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_5_fu_636_p2 = ((p_Result_63_fu_622_p4 < zext_ln443_4_fu_632_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_6_fu_718_p2 = ((p_Result_66_fu_704_p4 < zext_ln443_5_fu_714_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_7_fu_793_p2 = ((p_Result_69_fu_779_p4 < zext_ln443_6_fu_789_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_8_fu_875_p2 = ((p_Result_72_fu_861_p4 < zext_ln443_7_fu_871_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_9_fu_957_p2 = ((p_Result_75_fu_943_p4 < zext_ln443_8_fu_953_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_fu_232_p2 = ((tmp_fu_222_p4 == 2'd0) ? 1'b1 : 1'b0);

assign mul_I_V_fu_1483_p3 = {{17'd0}, {res_I_V_46_fu_1475_p3}};

assign p_Result_10_fu_522_p4 = {{res_I_V_35_fu_514_p3[15:11]}};

assign p_Result_13_fu_604_p4 = {{res_I_V_36_fu_596_p3[15:10]}};

assign p_Result_16_fu_686_p4 = {{res_I_V_37_fu_678_p3[15:9]}};

assign p_Result_19_fu_761_p4 = {{res_I_V_38_fu_755_p3[15:8]}};

assign p_Result_22_fu_843_p4 = {{res_I_V_fu_835_p3[15:7]}};

assign p_Result_25_fu_925_p4 = {{res_I_V_39_fu_917_p3[15:6]}};

assign p_Result_28_fu_1007_p4 = {{res_I_V_40_fu_999_p3[15:5]}};

assign p_Result_31_fu_1089_p4 = {{res_I_V_41_fu_1081_p3[15:4]}};

assign p_Result_37_fu_1253_p4 = {{res_I_V_43_fu_1246_p3[15:2]}};

assign p_Result_40_fu_1335_p4 = {{res_I_V_44_fu_1327_p3[15:1]}};

assign p_Result_48_fu_1495_p2 = ((x_l_I_V_45_fu_1467_p3 > zext_ln671_fu_1491_p1) ? 1'b1 : 1'b0);

assign p_Result_4_fu_358_p4 = {{res_I_V_33_fu_350_p3[15:13]}};

assign p_Result_50_fu_251_p5 = {{zext_ln666_fu_248_p1[34:33]}, {add_ln212_reg_1535}, {zext_ln666_fu_248_p1[29:0]}};

assign p_Result_51_fu_294_p4 = {{x_l_I_V_31_fu_262_p3[31:28]}};

assign p_Result_52_fu_320_p5 = {{x_l_I_V_31_fu_262_p3[34:32]}, {sub_ln212_fu_314_p2}, {x_l_I_V_31_fu_262_p3[27:0]}};

assign p_Result_53_fu_332_p4 = {res_I_V_32_fu_269_p3[16 - 1:15], |(1'd1), res_I_V_32_fu_269_p3[13:0]};

assign p_Result_54_fu_376_p4 = {{x_l_I_V_32_fu_342_p3[30:26]}};

assign p_Result_55_fu_402_p5 = {{x_l_I_V_32_fu_342_p3[34:31]}, {sub_ln212_1_fu_396_p2}, {x_l_I_V_32_fu_342_p3[25:0]}};

assign p_Result_56_fu_414_p4 = {res_I_V_33_fu_350_p3[16 - 1:14], |(1'd1), res_I_V_33_fu_350_p3[12:0]};

assign p_Result_57_fu_458_p4 = {{x_l_I_V_33_fu_424_p3[29:24]}};

assign p_Result_58_fu_484_p5 = {{x_l_I_V_33_fu_424_p3[34:30]}, {sub_ln212_2_fu_478_p2}, {x_l_I_V_33_fu_424_p3[23:0]}};

assign p_Result_59_fu_496_p4 = {res_I_V_34_fu_432_p3[16 - 1:13], |(1'd1), res_I_V_34_fu_432_p3[11:0]};

assign p_Result_60_fu_540_p4 = {{x_l_I_V_34_fu_506_p3[28:22]}};

assign p_Result_61_fu_566_p5 = {{x_l_I_V_34_fu_506_p3[34:29]}, {sub_ln212_3_fu_560_p2}, {x_l_I_V_34_fu_506_p3[21:0]}};

assign p_Result_62_fu_578_p4 = {res_I_V_35_fu_514_p3[16 - 1:12], |(1'd1), res_I_V_35_fu_514_p3[10:0]};

assign p_Result_63_fu_622_p4 = {{x_l_I_V_35_fu_588_p3[27:20]}};

assign p_Result_64_fu_648_p5 = {{x_l_I_V_35_fu_588_p3[34:28]}, {sub_ln212_4_fu_642_p2}, {x_l_I_V_35_fu_588_p3[19:0]}};

assign p_Result_65_fu_660_p4 = {res_I_V_36_fu_596_p3[16 - 1:11], |(1'd1), res_I_V_36_fu_596_p3[9:0]};

assign p_Result_66_fu_704_p4 = {{x_l_I_V_36_fu_670_p3[26:18]}};

assign p_Result_67_fu_730_p5 = {{x_l_I_V_36_reg_1540[34:27]}, {sub_ln212_5_reg_1558}, {x_l_I_V_36_reg_1540[17:0]}};

assign p_Result_68_fu_740_p4 = {res_I_V_37_reg_1546[16 - 1:10], |(1'd1), res_I_V_37_reg_1546[8:0]};

assign p_Result_69_fu_779_p4 = {{x_l_I_V_fu_749_p3[25:16]}};

assign p_Result_70_fu_805_p5 = {{x_l_I_V_fu_749_p3[34:26]}, {sub_ln212_6_fu_799_p2}, {x_l_I_V_fu_749_p3[15:0]}};

assign p_Result_71_fu_817_p4 = {res_I_V_38_fu_755_p3[16 - 1:9], |(1'd1), res_I_V_38_fu_755_p3[7:0]};

assign p_Result_72_fu_861_p4 = {{x_l_I_V_37_fu_827_p3[24:14]}};

assign p_Result_73_fu_887_p5 = {{x_l_I_V_37_fu_827_p3[34:25]}, {sub_ln212_7_fu_881_p2}, {x_l_I_V_37_fu_827_p3[13:0]}};

assign p_Result_74_fu_899_p4 = {res_I_V_fu_835_p3[16 - 1:8], |(1'd1), res_I_V_fu_835_p3[6:0]};

assign p_Result_75_fu_943_p4 = {{x_l_I_V_38_fu_909_p3[23:12]}};

assign p_Result_76_fu_969_p5 = {{x_l_I_V_38_fu_909_p3[34:24]}, {sub_ln212_8_fu_963_p2}, {x_l_I_V_38_fu_909_p3[11:0]}};

assign p_Result_77_fu_981_p4 = {res_I_V_39_fu_917_p3[16 - 1:7], |(1'd1), res_I_V_39_fu_917_p3[5:0]};

assign p_Result_78_fu_1025_p4 = {{x_l_I_V_39_fu_991_p3[22:10]}};

assign p_Result_79_fu_1051_p5 = {{x_l_I_V_39_fu_991_p3[34:23]}, {sub_ln212_9_fu_1045_p2}, {x_l_I_V_39_fu_991_p3[9:0]}};

assign p_Result_80_fu_1063_p4 = {res_I_V_40_fu_999_p3[16 - 1:6], |(1'd1), res_I_V_40_fu_999_p3[4:0]};

assign p_Result_81_fu_1107_p4 = {{x_l_I_V_40_fu_1073_p3[21:8]}};

assign p_Result_82_fu_1133_p5 = {{x_l_I_V_40_fu_1073_p3[34:22]}, {sub_ln212_10_fu_1127_p2}, {x_l_I_V_40_fu_1073_p3[7:0]}};

assign p_Result_83_fu_1145_p4 = {res_I_V_41_fu_1081_p3[16 - 1:5], |(1'd1), res_I_V_41_fu_1081_p3[3:0]};

assign p_Result_85_fu_1219_p5 = {{x_l_I_V_41_reg_1563[34:21]}, {sub_ln212_11_fu_1214_p2}, {x_l_I_V_41_reg_1563[5:0]}};

assign p_Result_86_fu_1230_p4 = {res_I_V_42_reg_1569[16 - 1:4], |(1'd1), res_I_V_42_reg_1569[2:0]};

assign p_Result_87_fu_1271_p4 = {{x_l_I_V_42_fu_1239_p3[19:4]}};

assign p_Result_88_fu_1297_p5 = {{x_l_I_V_42_fu_1239_p3[34:20]}, {sub_ln212_12_fu_1291_p2}, {x_l_I_V_42_fu_1239_p3[3:0]}};

assign p_Result_89_fu_1309_p4 = {res_I_V_43_fu_1246_p3[16 - 1:3], |(1'd1), res_I_V_43_fu_1246_p3[1:0]};

assign p_Result_8_fu_440_p4 = {{res_I_V_34_fu_432_p3[15:12]}};

assign p_Result_90_fu_1353_p4 = {{x_l_I_V_43_fu_1319_p3[18:2]}};

assign p_Result_91_fu_1379_p5 = {{x_l_I_V_43_fu_1319_p3[34:19]}, {sub_ln212_13_fu_1373_p2}, {x_l_I_V_43_fu_1319_p3[1:0]}};

assign p_Result_92_fu_1391_p4 = {res_I_V_44_fu_1327_p3[16 - 1:2], |(1'd1), res_I_V_44_fu_1327_p3[0:0]};

assign p_Result_93_fu_1425_p1 = x_l_I_V_44_fu_1401_p3[17:0];

assign p_Result_94_fu_1445_p5 = {{x_l_I_V_44_fu_1401_p3[34:18]}, {sub_ln212_14_fu_1439_p2}};

assign p_Result_95_fu_1457_p4 = {res_I_V_45_fu_1409_p3[16-1:1], |(1'd1)};

assign p_Result_s_66_fu_276_p4 = {{res_I_V_32_fu_269_p3[15:14]}};

assign p_Result_s_fu_1191_p3 = x_read_reg_1523_pp0_iter2_reg[32'd31];

assign res_I_V_30_fu_1501_p2 = (res_I_V_46_fu_1475_p3 + 16'd1);

assign res_I_V_32_fu_269_p3 = ((icmp_ln443_reg_1529[0:0] == 1'b1) ? 16'd0 : 16'd32768);

assign res_I_V_33_fu_350_p3 = ((icmp_ln443_1_fu_308_p2[0:0] == 1'b1) ? res_I_V_32_fu_269_p3 : p_Result_53_fu_332_p4);

assign res_I_V_34_fu_432_p3 = ((icmp_ln443_2_fu_390_p2[0:0] == 1'b1) ? res_I_V_33_fu_350_p3 : p_Result_56_fu_414_p4);

assign res_I_V_35_fu_514_p3 = ((icmp_ln443_3_fu_472_p2[0:0] == 1'b1) ? res_I_V_34_fu_432_p3 : p_Result_59_fu_496_p4);

assign res_I_V_36_fu_596_p3 = ((icmp_ln443_4_fu_554_p2[0:0] == 1'b1) ? res_I_V_35_fu_514_p3 : p_Result_62_fu_578_p4);

assign res_I_V_37_fu_678_p3 = ((icmp_ln443_5_fu_636_p2[0:0] == 1'b1) ? res_I_V_36_fu_596_p3 : p_Result_65_fu_660_p4);

assign res_I_V_38_fu_755_p3 = ((icmp_ln443_6_reg_1552[0:0] == 1'b1) ? res_I_V_37_reg_1546 : p_Result_68_fu_740_p4);

assign res_I_V_39_fu_917_p3 = ((icmp_ln443_8_fu_875_p2[0:0] == 1'b1) ? res_I_V_fu_835_p3 : p_Result_74_fu_899_p4);

assign res_I_V_40_fu_999_p3 = ((icmp_ln443_9_fu_957_p2[0:0] == 1'b1) ? res_I_V_39_fu_917_p3 : p_Result_77_fu_981_p4);

assign res_I_V_41_fu_1081_p3 = ((icmp_ln443_10_fu_1039_p2[0:0] == 1'b1) ? res_I_V_40_fu_999_p3 : p_Result_80_fu_1063_p4);

assign res_I_V_42_fu_1163_p3 = ((icmp_ln443_11_fu_1121_p2[0:0] == 1'b1) ? res_I_V_41_fu_1081_p3 : p_Result_83_fu_1145_p4);

assign res_I_V_43_fu_1246_p3 = ((icmp_ln443_12_fu_1209_p2[0:0] == 1'b1) ? res_I_V_42_reg_1569 : p_Result_86_fu_1230_p4);

assign res_I_V_44_fu_1327_p3 = ((icmp_ln443_13_fu_1285_p2[0:0] == 1'b1) ? res_I_V_43_fu_1246_p3 : p_Result_89_fu_1309_p4);

assign res_I_V_45_fu_1409_p3 = ((icmp_ln443_14_fu_1367_p2[0:0] == 1'b1) ? res_I_V_44_fu_1327_p3 : p_Result_92_fu_1391_p4);

assign res_I_V_46_fu_1475_p3 = ((icmp_ln443_15_fu_1433_p2[0:0] == 1'b1) ? res_I_V_45_fu_1409_p3 : p_Result_95_fu_1457_p4);

assign res_I_V_47_fu_1507_p3 = ((p_Result_48_fu_1495_p2[0:0] == 1'b1) ? res_I_V_30_fu_1501_p2 : res_I_V_46_fu_1475_p3);

assign res_I_V_fu_835_p3 = ((icmp_ln443_7_fu_793_p2[0:0] == 1'b1) ? res_I_V_38_fu_755_p3 : p_Result_71_fu_817_p4);

assign select_ln53_fu_1515_p3 = ((p_Result_s_fu_1191_p3[0:0] == 1'b1) ? 16'd0 : res_I_V_47_fu_1507_p3);

assign sub_ln212_10_fu_1127_p2 = (p_Result_81_fu_1107_p4 - zext_ln443_10_fu_1117_p1);

assign sub_ln212_11_fu_1214_p2 = (p_Result_84_reg_1580 - zext_ln443_11_fu_1205_p1);

assign sub_ln212_12_fu_1291_p2 = (p_Result_87_fu_1271_p4 - zext_ln443_12_fu_1281_p1);

assign sub_ln212_13_fu_1373_p2 = (p_Result_90_fu_1353_p4 - zext_ln443_13_fu_1363_p1);

assign sub_ln212_14_fu_1439_p2 = (p_Result_93_fu_1425_p1 - zext_ln443_14_fu_1429_p1);

assign sub_ln212_1_fu_396_p2 = (p_Result_54_fu_376_p4 - zext_ln443_1_fu_386_p1);

assign sub_ln212_2_fu_478_p2 = (p_Result_57_fu_458_p4 - zext_ln443_2_fu_468_p1);

assign sub_ln212_3_fu_560_p2 = (p_Result_60_fu_540_p4 - zext_ln443_3_fu_550_p1);

assign sub_ln212_4_fu_642_p2 = (p_Result_63_fu_622_p4 - zext_ln443_4_fu_632_p1);

assign sub_ln212_5_fu_724_p2 = (p_Result_66_fu_704_p4 - zext_ln443_5_fu_714_p1);

assign sub_ln212_6_fu_799_p2 = (p_Result_69_fu_779_p4 - zext_ln443_6_fu_789_p1);

assign sub_ln212_7_fu_881_p2 = (p_Result_72_fu_861_p4 - zext_ln443_7_fu_871_p1);

assign sub_ln212_8_fu_963_p2 = (p_Result_75_fu_943_p4 - zext_ln443_8_fu_953_p1);

assign sub_ln212_9_fu_1045_p2 = (p_Result_78_fu_1025_p4 - zext_ln443_9_fu_1035_p1);

assign sub_ln212_fu_314_p2 = (p_Result_51_fu_294_p4 - zext_ln443_fu_304_p1);

assign tmp_10_fu_1099_p3 = {{p_Result_31_fu_1089_p4}, {1'd1}};

assign tmp_11_fu_1198_p3 = {{p_Result_34_reg_1575}, {1'd1}};

assign tmp_12_fu_1263_p3 = {{p_Result_37_fu_1253_p4}, {1'd1}};

assign tmp_13_fu_1345_p3 = {{p_Result_40_fu_1335_p4}, {1'd1}};

assign tmp_14_fu_1417_p3 = {{res_I_V_45_fu_1409_p3}, {1'd1}};

assign tmp_1_fu_286_p3 = {{p_Result_s_66_fu_276_p4}, {1'd1}};

assign tmp_2_fu_368_p3 = {{p_Result_4_fu_358_p4}, {1'd1}};

assign tmp_3_fu_450_p3 = {{p_Result_8_fu_440_p4}, {1'd1}};

assign tmp_4_fu_532_p3 = {{p_Result_10_fu_522_p4}, {1'd1}};

assign tmp_5_fu_614_p3 = {{p_Result_13_fu_604_p4}, {1'd1}};

assign tmp_6_fu_696_p3 = {{p_Result_16_fu_686_p4}, {1'd1}};

assign tmp_7_fu_771_p3 = {{p_Result_19_fu_761_p4}, {1'd1}};

assign tmp_8_fu_853_p3 = {{p_Result_22_fu_843_p4}, {1'd1}};

assign tmp_9_fu_935_p3 = {{p_Result_25_fu_925_p4}, {1'd1}};

assign tmp_fu_222_p4 = {{x_int_reg[31:30]}};

assign tmp_s_fu_1017_p3 = {{p_Result_28_fu_1007_p4}, {1'd1}};

assign x_l_I_V_31_fu_262_p3 = ((icmp_ln443_reg_1529[0:0] == 1'b1) ? zext_ln666_fu_248_p1 : p_Result_50_fu_251_p5);

assign x_l_I_V_32_fu_342_p3 = ((icmp_ln443_1_fu_308_p2[0:0] == 1'b1) ? x_l_I_V_31_fu_262_p3 : p_Result_52_fu_320_p5);

assign x_l_I_V_33_fu_424_p3 = ((icmp_ln443_2_fu_390_p2[0:0] == 1'b1) ? x_l_I_V_32_fu_342_p3 : p_Result_55_fu_402_p5);

assign x_l_I_V_34_fu_506_p3 = ((icmp_ln443_3_fu_472_p2[0:0] == 1'b1) ? x_l_I_V_33_fu_424_p3 : p_Result_58_fu_484_p5);

assign x_l_I_V_35_fu_588_p3 = ((icmp_ln443_4_fu_554_p2[0:0] == 1'b1) ? x_l_I_V_34_fu_506_p3 : p_Result_61_fu_566_p5);

assign x_l_I_V_36_fu_670_p3 = ((icmp_ln443_5_fu_636_p2[0:0] == 1'b1) ? x_l_I_V_35_fu_588_p3 : p_Result_64_fu_648_p5);

assign x_l_I_V_37_fu_827_p3 = ((icmp_ln443_7_fu_793_p2[0:0] == 1'b1) ? x_l_I_V_fu_749_p3 : p_Result_70_fu_805_p5);

assign x_l_I_V_38_fu_909_p3 = ((icmp_ln443_8_fu_875_p2[0:0] == 1'b1) ? x_l_I_V_37_fu_827_p3 : p_Result_73_fu_887_p5);

assign x_l_I_V_39_fu_991_p3 = ((icmp_ln443_9_fu_957_p2[0:0] == 1'b1) ? x_l_I_V_38_fu_909_p3 : p_Result_76_fu_969_p5);

assign x_l_I_V_40_fu_1073_p3 = ((icmp_ln443_10_fu_1039_p2[0:0] == 1'b1) ? x_l_I_V_39_fu_991_p3 : p_Result_79_fu_1051_p5);

assign x_l_I_V_41_fu_1155_p3 = ((icmp_ln443_11_fu_1121_p2[0:0] == 1'b1) ? x_l_I_V_40_fu_1073_p3 : p_Result_82_fu_1133_p5);

assign x_l_I_V_42_fu_1239_p3 = ((icmp_ln443_12_fu_1209_p2[0:0] == 1'b1) ? x_l_I_V_41_reg_1563 : p_Result_85_fu_1219_p5);

assign x_l_I_V_43_fu_1319_p3 = ((icmp_ln443_13_fu_1285_p2[0:0] == 1'b1) ? x_l_I_V_42_fu_1239_p3 : p_Result_88_fu_1297_p5);

assign x_l_I_V_44_fu_1401_p3 = ((icmp_ln443_14_fu_1367_p2[0:0] == 1'b1) ? x_l_I_V_43_fu_1319_p3 : p_Result_91_fu_1379_p5);

assign x_l_I_V_45_fu_1467_p3 = ((icmp_ln443_15_fu_1433_p2[0:0] == 1'b1) ? x_l_I_V_44_fu_1401_p3 : p_Result_94_fu_1445_p5);

assign x_l_I_V_fu_749_p3 = ((icmp_ln443_6_reg_1552[0:0] == 1'b1) ? x_l_I_V_36_reg_1540 : p_Result_67_fu_730_p5);

assign zext_ln212_fu_238_p1 = tmp_fu_222_p4;

assign zext_ln443_10_fu_1117_p1 = tmp_10_fu_1099_p3;

assign zext_ln443_11_fu_1205_p1 = tmp_11_fu_1198_p3;

assign zext_ln443_12_fu_1281_p1 = tmp_12_fu_1263_p3;

assign zext_ln443_13_fu_1363_p1 = tmp_13_fu_1345_p3;

assign zext_ln443_14_fu_1429_p1 = tmp_14_fu_1417_p3;

assign zext_ln443_1_fu_386_p1 = tmp_2_fu_368_p3;

assign zext_ln443_2_fu_468_p1 = tmp_3_fu_450_p3;

assign zext_ln443_3_fu_550_p1 = tmp_4_fu_532_p3;

assign zext_ln443_4_fu_632_p1 = tmp_5_fu_614_p3;

assign zext_ln443_5_fu_714_p1 = tmp_6_fu_696_p3;

assign zext_ln443_6_fu_789_p1 = tmp_7_fu_771_p3;

assign zext_ln443_7_fu_871_p1 = tmp_8_fu_853_p3;

assign zext_ln443_8_fu_953_p1 = tmp_9_fu_935_p3;

assign zext_ln443_9_fu_1035_p1 = tmp_s_fu_1017_p3;

assign zext_ln443_fu_304_p1 = tmp_1_fu_286_p3;

assign zext_ln666_fu_248_p1 = x_read_reg_1523;

assign zext_ln671_fu_1491_p1 = mul_I_V_fu_1483_p3;

endmodule //sobel_sqrt_fixed_32_32_s
