-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_sqrt_fixed_32_32_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of sobel_sqrt_fixed_32_32_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal x_read_reg_1523 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal x_read_reg_1523_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal x_read_reg_1523_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln443_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln443_reg_1529 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln212_fu_242_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln212_reg_1535 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_l_I_V_36_fu_670_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_36_reg_1540 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_37_fu_678_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_37_reg_1546 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln443_6_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln443_6_reg_1552 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln212_5_fu_724_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln212_5_reg_1558 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_l_I_V_41_fu_1155_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_l_I_V_41_reg_1563 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_42_fu_1163_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_42_reg_1569 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_34_reg_1575 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_84_reg_1580 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_fu_222_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln212_fu_238_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln666_fu_248_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_50_fu_251_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal res_I_V_32_fu_269_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_66_fu_276_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal x_l_I_V_31_fu_262_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_1_fu_286_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_51_fu_294_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln443_fu_304_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln212_fu_314_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln443_1_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_52_fu_320_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_53_fu_332_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_33_fu_350_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_4_fu_358_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_l_I_V_32_fu_342_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_2_fu_368_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_54_fu_376_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln443_1_fu_386_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln212_1_fu_396_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln443_2_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_55_fu_402_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_56_fu_414_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_34_fu_432_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_8_fu_440_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_l_I_V_33_fu_424_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_3_fu_450_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Result_57_fu_458_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln443_2_fu_468_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln212_2_fu_478_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln443_3_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_58_fu_484_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_59_fu_496_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_35_fu_514_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_10_fu_522_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_l_I_V_34_fu_506_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_4_fu_532_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_60_fu_540_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln443_3_fu_550_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln212_3_fu_560_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln443_4_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_61_fu_566_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_62_fu_578_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_36_fu_596_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_13_fu_604_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_l_I_V_35_fu_588_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_5_fu_614_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Result_63_fu_622_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln443_4_fu_632_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln212_4_fu_642_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln443_5_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_64_fu_648_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_65_fu_660_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_16_fu_686_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_6_fu_696_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_66_fu_704_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln443_5_fu_714_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_67_fu_730_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_68_fu_740_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_38_fu_755_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_19_fu_761_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_l_I_V_fu_749_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_7_fu_771_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_69_fu_779_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln443_6_fu_789_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln212_6_fu_799_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln443_7_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_70_fu_805_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_71_fu_817_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_fu_835_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_22_fu_843_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_l_I_V_37_fu_827_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_8_fu_853_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Result_72_fu_861_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln443_7_fu_871_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln212_7_fu_881_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln443_8_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_73_fu_887_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_74_fu_899_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_39_fu_917_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_25_fu_925_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal x_l_I_V_38_fu_909_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_9_fu_935_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_75_fu_943_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln443_8_fu_953_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln212_8_fu_963_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln443_9_fu_957_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_76_fu_969_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_77_fu_981_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_40_fu_999_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_28_fu_1007_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_l_I_V_39_fu_991_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_s_fu_1017_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_78_fu_1025_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln443_9_fu_1035_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln212_9_fu_1045_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln443_10_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_79_fu_1051_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_80_fu_1063_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_41_fu_1081_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_31_fu_1089_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_l_I_V_40_fu_1073_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_10_fu_1099_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_81_fu_1107_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln443_10_fu_1117_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln212_10_fu_1127_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln443_11_fu_1121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_82_fu_1133_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_83_fu_1145_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_1198_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln443_11_fu_1205_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sub_ln212_11_fu_1214_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln443_12_fu_1209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_85_fu_1219_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_86_fu_1230_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_43_fu_1246_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_37_fu_1253_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal x_l_I_V_42_fu_1239_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_12_fu_1263_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Result_87_fu_1271_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln443_12_fu_1281_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln212_12_fu_1291_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln443_13_fu_1285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_88_fu_1297_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_89_fu_1309_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_44_fu_1327_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_40_fu_1335_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal x_l_I_V_43_fu_1319_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_13_fu_1345_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_90_fu_1353_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln443_13_fu_1363_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln212_13_fu_1373_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln443_14_fu_1367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_91_fu_1379_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_92_fu_1391_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_45_fu_1409_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_l_I_V_44_fu_1401_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_14_fu_1417_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Result_93_fu_1425_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln443_14_fu_1429_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln212_14_fu_1439_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln443_15_fu_1433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_94_fu_1445_p5 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_95_fu_1457_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_I_V_46_fu_1475_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_I_V_fu_1483_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal x_l_I_V_45_fu_1467_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal zext_ln671_fu_1491_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal p_Result_48_fu_1495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_I_V_30_fu_1501_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_1191_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_I_V_47_fu_1507_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln53_fu_1515_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal x_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (15 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln212_reg_1535 <= add_ln212_fu_242_p2;
                icmp_ln443_6_reg_1552 <= icmp_ln443_6_fu_718_p2;
                icmp_ln443_reg_1529 <= icmp_ln443_fu_232_p2;
                p_Result_34_reg_1575 <= res_I_V_42_fu_1163_p3(15 downto 3);
                p_Result_84_reg_1580 <= x_l_I_V_41_fu_1155_p3(20 downto 6);
                res_I_V_37_reg_1546 <= res_I_V_37_fu_678_p3;
                res_I_V_42_reg_1569 <= res_I_V_42_fu_1163_p3;
                sub_ln212_5_reg_1558 <= sub_ln212_5_fu_724_p2;
                x_l_I_V_36_reg_1540 <= x_l_I_V_36_fu_670_p3;
                x_l_I_V_41_reg_1563 <= x_l_I_V_41_fu_1155_p3;
                x_read_reg_1523 <= x_int_reg;
                x_read_reg_1523_pp0_iter1_reg <= x_read_reg_1523;
                x_read_reg_1523_pp0_iter2_reg <= x_read_reg_1523_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= select_ln53_fu_1515_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                x_int_reg <= x;
            end if;
        end if;
    end process;
    add_ln212_fu_242_p2 <= std_logic_vector(unsigned(zext_ln212_fu_238_p1) + unsigned(ap_const_lv3_7));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(select_ln53_fu_1515_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= select_ln53_fu_1515_p3;
        else 
            ap_return <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln443_10_fu_1039_p2 <= "1" when (unsigned(p_Result_78_fu_1025_p4) < unsigned(zext_ln443_9_fu_1035_p1)) else "0";
    icmp_ln443_11_fu_1121_p2 <= "1" when (unsigned(p_Result_81_fu_1107_p4) < unsigned(zext_ln443_10_fu_1117_p1)) else "0";
    icmp_ln443_12_fu_1209_p2 <= "1" when (unsigned(p_Result_84_reg_1580) < unsigned(zext_ln443_11_fu_1205_p1)) else "0";
    icmp_ln443_13_fu_1285_p2 <= "1" when (unsigned(p_Result_87_fu_1271_p4) < unsigned(zext_ln443_12_fu_1281_p1)) else "0";
    icmp_ln443_14_fu_1367_p2 <= "1" when (unsigned(p_Result_90_fu_1353_p4) < unsigned(zext_ln443_13_fu_1363_p1)) else "0";
    icmp_ln443_15_fu_1433_p2 <= "1" when (unsigned(p_Result_93_fu_1425_p1) < unsigned(zext_ln443_14_fu_1429_p1)) else "0";
    icmp_ln443_1_fu_308_p2 <= "1" when (unsigned(p_Result_51_fu_294_p4) < unsigned(zext_ln443_fu_304_p1)) else "0";
    icmp_ln443_2_fu_390_p2 <= "1" when (unsigned(p_Result_54_fu_376_p4) < unsigned(zext_ln443_1_fu_386_p1)) else "0";
    icmp_ln443_3_fu_472_p2 <= "1" when (unsigned(p_Result_57_fu_458_p4) < unsigned(zext_ln443_2_fu_468_p1)) else "0";
    icmp_ln443_4_fu_554_p2 <= "1" when (unsigned(p_Result_60_fu_540_p4) < unsigned(zext_ln443_3_fu_550_p1)) else "0";
    icmp_ln443_5_fu_636_p2 <= "1" when (unsigned(p_Result_63_fu_622_p4) < unsigned(zext_ln443_4_fu_632_p1)) else "0";
    icmp_ln443_6_fu_718_p2 <= "1" when (unsigned(p_Result_66_fu_704_p4) < unsigned(zext_ln443_5_fu_714_p1)) else "0";
    icmp_ln443_7_fu_793_p2 <= "1" when (unsigned(p_Result_69_fu_779_p4) < unsigned(zext_ln443_6_fu_789_p1)) else "0";
    icmp_ln443_8_fu_875_p2 <= "1" when (unsigned(p_Result_72_fu_861_p4) < unsigned(zext_ln443_7_fu_871_p1)) else "0";
    icmp_ln443_9_fu_957_p2 <= "1" when (unsigned(p_Result_75_fu_943_p4) < unsigned(zext_ln443_8_fu_953_p1)) else "0";
    icmp_ln443_fu_232_p2 <= "1" when (tmp_fu_222_p4 = ap_const_lv2_0) else "0";
    mul_I_V_fu_1483_p3 <= (ap_const_lv17_0 & res_I_V_46_fu_1475_p3);
    p_Result_10_fu_522_p4 <= res_I_V_35_fu_514_p3(15 downto 11);
    p_Result_13_fu_604_p4 <= res_I_V_36_fu_596_p3(15 downto 10);
    p_Result_16_fu_686_p4 <= res_I_V_37_fu_678_p3(15 downto 9);
    p_Result_19_fu_761_p4 <= res_I_V_38_fu_755_p3(15 downto 8);
    p_Result_22_fu_843_p4 <= res_I_V_fu_835_p3(15 downto 7);
    p_Result_25_fu_925_p4 <= res_I_V_39_fu_917_p3(15 downto 6);
    p_Result_28_fu_1007_p4 <= res_I_V_40_fu_999_p3(15 downto 5);
    p_Result_31_fu_1089_p4 <= res_I_V_41_fu_1081_p3(15 downto 4);
    p_Result_37_fu_1253_p4 <= res_I_V_43_fu_1246_p3(15 downto 2);
    p_Result_40_fu_1335_p4 <= res_I_V_44_fu_1327_p3(15 downto 1);
    p_Result_48_fu_1495_p2 <= "1" when (unsigned(x_l_I_V_45_fu_1467_p3) > unsigned(zext_ln671_fu_1491_p1)) else "0";
    p_Result_4_fu_358_p4 <= res_I_V_33_fu_350_p3(15 downto 13);
    p_Result_50_fu_251_p5 <= (zext_ln666_fu_248_p1(34 downto 33) & add_ln212_reg_1535 & zext_ln666_fu_248_p1(29 downto 0));
    p_Result_51_fu_294_p4 <= x_l_I_V_31_fu_262_p3(31 downto 28);
    p_Result_52_fu_320_p5 <= (x_l_I_V_31_fu_262_p3(34 downto 32) & sub_ln212_fu_314_p2 & x_l_I_V_31_fu_262_p3(27 downto 0));
    
    p_Result_53_fu_332_p4_proc : process(res_I_V_32_fu_269_p3)
    begin
        p_Result_53_fu_332_p4 <= res_I_V_32_fu_269_p3;
        p_Result_53_fu_332_p4(14) <= ap_const_lv1_1(0);
    end process;

    p_Result_54_fu_376_p4 <= x_l_I_V_32_fu_342_p3(30 downto 26);
    p_Result_55_fu_402_p5 <= (x_l_I_V_32_fu_342_p3(34 downto 31) & sub_ln212_1_fu_396_p2 & x_l_I_V_32_fu_342_p3(25 downto 0));
    
    p_Result_56_fu_414_p4_proc : process(res_I_V_33_fu_350_p3)
    begin
        p_Result_56_fu_414_p4 <= res_I_V_33_fu_350_p3;
        p_Result_56_fu_414_p4(13) <= ap_const_lv1_1(0);
    end process;

    p_Result_57_fu_458_p4 <= x_l_I_V_33_fu_424_p3(29 downto 24);
    p_Result_58_fu_484_p5 <= (x_l_I_V_33_fu_424_p3(34 downto 30) & sub_ln212_2_fu_478_p2 & x_l_I_V_33_fu_424_p3(23 downto 0));
    
    p_Result_59_fu_496_p4_proc : process(res_I_V_34_fu_432_p3)
    begin
        p_Result_59_fu_496_p4 <= res_I_V_34_fu_432_p3;
        p_Result_59_fu_496_p4(12) <= ap_const_lv1_1(0);
    end process;

    p_Result_60_fu_540_p4 <= x_l_I_V_34_fu_506_p3(28 downto 22);
    p_Result_61_fu_566_p5 <= (x_l_I_V_34_fu_506_p3(34 downto 29) & sub_ln212_3_fu_560_p2 & x_l_I_V_34_fu_506_p3(21 downto 0));
    
    p_Result_62_fu_578_p4_proc : process(res_I_V_35_fu_514_p3)
    begin
        p_Result_62_fu_578_p4 <= res_I_V_35_fu_514_p3;
        p_Result_62_fu_578_p4(11) <= ap_const_lv1_1(0);
    end process;

    p_Result_63_fu_622_p4 <= x_l_I_V_35_fu_588_p3(27 downto 20);
    p_Result_64_fu_648_p5 <= (x_l_I_V_35_fu_588_p3(34 downto 28) & sub_ln212_4_fu_642_p2 & x_l_I_V_35_fu_588_p3(19 downto 0));
    
    p_Result_65_fu_660_p4_proc : process(res_I_V_36_fu_596_p3)
    begin
        p_Result_65_fu_660_p4 <= res_I_V_36_fu_596_p3;
        p_Result_65_fu_660_p4(10) <= ap_const_lv1_1(0);
    end process;

    p_Result_66_fu_704_p4 <= x_l_I_V_36_fu_670_p3(26 downto 18);
    p_Result_67_fu_730_p5 <= (x_l_I_V_36_reg_1540(34 downto 27) & sub_ln212_5_reg_1558 & x_l_I_V_36_reg_1540(17 downto 0));
    
    p_Result_68_fu_740_p4_proc : process(res_I_V_37_reg_1546)
    begin
        p_Result_68_fu_740_p4 <= res_I_V_37_reg_1546;
        p_Result_68_fu_740_p4(9) <= ap_const_lv1_1(0);
    end process;

    p_Result_69_fu_779_p4 <= x_l_I_V_fu_749_p3(25 downto 16);
    p_Result_70_fu_805_p5 <= (x_l_I_V_fu_749_p3(34 downto 26) & sub_ln212_6_fu_799_p2 & x_l_I_V_fu_749_p3(15 downto 0));
    
    p_Result_71_fu_817_p4_proc : process(res_I_V_38_fu_755_p3)
    begin
        p_Result_71_fu_817_p4 <= res_I_V_38_fu_755_p3;
        p_Result_71_fu_817_p4(8) <= ap_const_lv1_1(0);
    end process;

    p_Result_72_fu_861_p4 <= x_l_I_V_37_fu_827_p3(24 downto 14);
    p_Result_73_fu_887_p5 <= (x_l_I_V_37_fu_827_p3(34 downto 25) & sub_ln212_7_fu_881_p2 & x_l_I_V_37_fu_827_p3(13 downto 0));
    
    p_Result_74_fu_899_p4_proc : process(res_I_V_fu_835_p3)
    begin
        p_Result_74_fu_899_p4 <= res_I_V_fu_835_p3;
        p_Result_74_fu_899_p4(7) <= ap_const_lv1_1(0);
    end process;

    p_Result_75_fu_943_p4 <= x_l_I_V_38_fu_909_p3(23 downto 12);
    p_Result_76_fu_969_p5 <= (x_l_I_V_38_fu_909_p3(34 downto 24) & sub_ln212_8_fu_963_p2 & x_l_I_V_38_fu_909_p3(11 downto 0));
    
    p_Result_77_fu_981_p4_proc : process(res_I_V_39_fu_917_p3)
    begin
        p_Result_77_fu_981_p4 <= res_I_V_39_fu_917_p3;
        p_Result_77_fu_981_p4(6) <= ap_const_lv1_1(0);
    end process;

    p_Result_78_fu_1025_p4 <= x_l_I_V_39_fu_991_p3(22 downto 10);
    p_Result_79_fu_1051_p5 <= (x_l_I_V_39_fu_991_p3(34 downto 23) & sub_ln212_9_fu_1045_p2 & x_l_I_V_39_fu_991_p3(9 downto 0));
    
    p_Result_80_fu_1063_p4_proc : process(res_I_V_40_fu_999_p3)
    begin
        p_Result_80_fu_1063_p4 <= res_I_V_40_fu_999_p3;
        p_Result_80_fu_1063_p4(5) <= ap_const_lv1_1(0);
    end process;

    p_Result_81_fu_1107_p4 <= x_l_I_V_40_fu_1073_p3(21 downto 8);
    p_Result_82_fu_1133_p5 <= (x_l_I_V_40_fu_1073_p3(34 downto 22) & sub_ln212_10_fu_1127_p2 & x_l_I_V_40_fu_1073_p3(7 downto 0));
    
    p_Result_83_fu_1145_p4_proc : process(res_I_V_41_fu_1081_p3)
    begin
        p_Result_83_fu_1145_p4 <= res_I_V_41_fu_1081_p3;
        p_Result_83_fu_1145_p4(4) <= ap_const_lv1_1(0);
    end process;

    p_Result_85_fu_1219_p5 <= (x_l_I_V_41_reg_1563(34 downto 21) & sub_ln212_11_fu_1214_p2 & x_l_I_V_41_reg_1563(5 downto 0));
    
    p_Result_86_fu_1230_p4_proc : process(res_I_V_42_reg_1569)
    begin
        p_Result_86_fu_1230_p4 <= res_I_V_42_reg_1569;
        p_Result_86_fu_1230_p4(3) <= ap_const_lv1_1(0);
    end process;

    p_Result_87_fu_1271_p4 <= x_l_I_V_42_fu_1239_p3(19 downto 4);
    p_Result_88_fu_1297_p5 <= (x_l_I_V_42_fu_1239_p3(34 downto 20) & sub_ln212_12_fu_1291_p2 & x_l_I_V_42_fu_1239_p3(3 downto 0));
    
    p_Result_89_fu_1309_p4_proc : process(res_I_V_43_fu_1246_p3)
    begin
        p_Result_89_fu_1309_p4 <= res_I_V_43_fu_1246_p3;
        p_Result_89_fu_1309_p4(2) <= ap_const_lv1_1(0);
    end process;

    p_Result_8_fu_440_p4 <= res_I_V_34_fu_432_p3(15 downto 12);
    p_Result_90_fu_1353_p4 <= x_l_I_V_43_fu_1319_p3(18 downto 2);
    p_Result_91_fu_1379_p5 <= (x_l_I_V_43_fu_1319_p3(34 downto 19) & sub_ln212_13_fu_1373_p2 & x_l_I_V_43_fu_1319_p3(1 downto 0));
    
    p_Result_92_fu_1391_p4_proc : process(res_I_V_44_fu_1327_p3)
    begin
        p_Result_92_fu_1391_p4 <= res_I_V_44_fu_1327_p3;
        p_Result_92_fu_1391_p4(1) <= ap_const_lv1_1(0);
    end process;

    p_Result_93_fu_1425_p1 <= x_l_I_V_44_fu_1401_p3(18 - 1 downto 0);
    p_Result_94_fu_1445_p5 <= (x_l_I_V_44_fu_1401_p3(34 downto 18) & sub_ln212_14_fu_1439_p2);
    
    p_Result_95_fu_1457_p4_proc : process(res_I_V_45_fu_1409_p3)
    begin
        p_Result_95_fu_1457_p4 <= res_I_V_45_fu_1409_p3;
        p_Result_95_fu_1457_p4(0) <= ap_const_lv1_1(0);
    end process;

    p_Result_s_66_fu_276_p4 <= res_I_V_32_fu_269_p3(15 downto 14);
    p_Result_s_fu_1191_p3 <= x_read_reg_1523_pp0_iter2_reg(31 downto 31);
    res_I_V_30_fu_1501_p2 <= std_logic_vector(unsigned(res_I_V_46_fu_1475_p3) + unsigned(ap_const_lv16_1));
    res_I_V_32_fu_269_p3 <= 
        ap_const_lv16_0 when (icmp_ln443_reg_1529(0) = '1') else 
        ap_const_lv16_8000;
    res_I_V_33_fu_350_p3 <= 
        res_I_V_32_fu_269_p3 when (icmp_ln443_1_fu_308_p2(0) = '1') else 
        p_Result_53_fu_332_p4;
    res_I_V_34_fu_432_p3 <= 
        res_I_V_33_fu_350_p3 when (icmp_ln443_2_fu_390_p2(0) = '1') else 
        p_Result_56_fu_414_p4;
    res_I_V_35_fu_514_p3 <= 
        res_I_V_34_fu_432_p3 when (icmp_ln443_3_fu_472_p2(0) = '1') else 
        p_Result_59_fu_496_p4;
    res_I_V_36_fu_596_p3 <= 
        res_I_V_35_fu_514_p3 when (icmp_ln443_4_fu_554_p2(0) = '1') else 
        p_Result_62_fu_578_p4;
    res_I_V_37_fu_678_p3 <= 
        res_I_V_36_fu_596_p3 when (icmp_ln443_5_fu_636_p2(0) = '1') else 
        p_Result_65_fu_660_p4;
    res_I_V_38_fu_755_p3 <= 
        res_I_V_37_reg_1546 when (icmp_ln443_6_reg_1552(0) = '1') else 
        p_Result_68_fu_740_p4;
    res_I_V_39_fu_917_p3 <= 
        res_I_V_fu_835_p3 when (icmp_ln443_8_fu_875_p2(0) = '1') else 
        p_Result_74_fu_899_p4;
    res_I_V_40_fu_999_p3 <= 
        res_I_V_39_fu_917_p3 when (icmp_ln443_9_fu_957_p2(0) = '1') else 
        p_Result_77_fu_981_p4;
    res_I_V_41_fu_1081_p3 <= 
        res_I_V_40_fu_999_p3 when (icmp_ln443_10_fu_1039_p2(0) = '1') else 
        p_Result_80_fu_1063_p4;
    res_I_V_42_fu_1163_p3 <= 
        res_I_V_41_fu_1081_p3 when (icmp_ln443_11_fu_1121_p2(0) = '1') else 
        p_Result_83_fu_1145_p4;
    res_I_V_43_fu_1246_p3 <= 
        res_I_V_42_reg_1569 when (icmp_ln443_12_fu_1209_p2(0) = '1') else 
        p_Result_86_fu_1230_p4;
    res_I_V_44_fu_1327_p3 <= 
        res_I_V_43_fu_1246_p3 when (icmp_ln443_13_fu_1285_p2(0) = '1') else 
        p_Result_89_fu_1309_p4;
    res_I_V_45_fu_1409_p3 <= 
        res_I_V_44_fu_1327_p3 when (icmp_ln443_14_fu_1367_p2(0) = '1') else 
        p_Result_92_fu_1391_p4;
    res_I_V_46_fu_1475_p3 <= 
        res_I_V_45_fu_1409_p3 when (icmp_ln443_15_fu_1433_p2(0) = '1') else 
        p_Result_95_fu_1457_p4;
    res_I_V_47_fu_1507_p3 <= 
        res_I_V_30_fu_1501_p2 when (p_Result_48_fu_1495_p2(0) = '1') else 
        res_I_V_46_fu_1475_p3;
    res_I_V_fu_835_p3 <= 
        res_I_V_38_fu_755_p3 when (icmp_ln443_7_fu_793_p2(0) = '1') else 
        p_Result_71_fu_817_p4;
    select_ln53_fu_1515_p3 <= 
        ap_const_lv16_0 when (p_Result_s_fu_1191_p3(0) = '1') else 
        res_I_V_47_fu_1507_p3;
    sub_ln212_10_fu_1127_p2 <= std_logic_vector(unsigned(p_Result_81_fu_1107_p4) - unsigned(zext_ln443_10_fu_1117_p1));
    sub_ln212_11_fu_1214_p2 <= std_logic_vector(unsigned(p_Result_84_reg_1580) - unsigned(zext_ln443_11_fu_1205_p1));
    sub_ln212_12_fu_1291_p2 <= std_logic_vector(unsigned(p_Result_87_fu_1271_p4) - unsigned(zext_ln443_12_fu_1281_p1));
    sub_ln212_13_fu_1373_p2 <= std_logic_vector(unsigned(p_Result_90_fu_1353_p4) - unsigned(zext_ln443_13_fu_1363_p1));
    sub_ln212_14_fu_1439_p2 <= std_logic_vector(unsigned(p_Result_93_fu_1425_p1) - unsigned(zext_ln443_14_fu_1429_p1));
    sub_ln212_1_fu_396_p2 <= std_logic_vector(unsigned(p_Result_54_fu_376_p4) - unsigned(zext_ln443_1_fu_386_p1));
    sub_ln212_2_fu_478_p2 <= std_logic_vector(unsigned(p_Result_57_fu_458_p4) - unsigned(zext_ln443_2_fu_468_p1));
    sub_ln212_3_fu_560_p2 <= std_logic_vector(unsigned(p_Result_60_fu_540_p4) - unsigned(zext_ln443_3_fu_550_p1));
    sub_ln212_4_fu_642_p2 <= std_logic_vector(unsigned(p_Result_63_fu_622_p4) - unsigned(zext_ln443_4_fu_632_p1));
    sub_ln212_5_fu_724_p2 <= std_logic_vector(unsigned(p_Result_66_fu_704_p4) - unsigned(zext_ln443_5_fu_714_p1));
    sub_ln212_6_fu_799_p2 <= std_logic_vector(unsigned(p_Result_69_fu_779_p4) - unsigned(zext_ln443_6_fu_789_p1));
    sub_ln212_7_fu_881_p2 <= std_logic_vector(unsigned(p_Result_72_fu_861_p4) - unsigned(zext_ln443_7_fu_871_p1));
    sub_ln212_8_fu_963_p2 <= std_logic_vector(unsigned(p_Result_75_fu_943_p4) - unsigned(zext_ln443_8_fu_953_p1));
    sub_ln212_9_fu_1045_p2 <= std_logic_vector(unsigned(p_Result_78_fu_1025_p4) - unsigned(zext_ln443_9_fu_1035_p1));
    sub_ln212_fu_314_p2 <= std_logic_vector(unsigned(p_Result_51_fu_294_p4) - unsigned(zext_ln443_fu_304_p1));
    tmp_10_fu_1099_p3 <= (p_Result_31_fu_1089_p4 & ap_const_lv1_1);
    tmp_11_fu_1198_p3 <= (p_Result_34_reg_1575 & ap_const_lv1_1);
    tmp_12_fu_1263_p3 <= (p_Result_37_fu_1253_p4 & ap_const_lv1_1);
    tmp_13_fu_1345_p3 <= (p_Result_40_fu_1335_p4 & ap_const_lv1_1);
    tmp_14_fu_1417_p3 <= (res_I_V_45_fu_1409_p3 & ap_const_lv1_1);
    tmp_1_fu_286_p3 <= (p_Result_s_66_fu_276_p4 & ap_const_lv1_1);
    tmp_2_fu_368_p3 <= (p_Result_4_fu_358_p4 & ap_const_lv1_1);
    tmp_3_fu_450_p3 <= (p_Result_8_fu_440_p4 & ap_const_lv1_1);
    tmp_4_fu_532_p3 <= (p_Result_10_fu_522_p4 & ap_const_lv1_1);
    tmp_5_fu_614_p3 <= (p_Result_13_fu_604_p4 & ap_const_lv1_1);
    tmp_6_fu_696_p3 <= (p_Result_16_fu_686_p4 & ap_const_lv1_1);
    tmp_7_fu_771_p3 <= (p_Result_19_fu_761_p4 & ap_const_lv1_1);
    tmp_8_fu_853_p3 <= (p_Result_22_fu_843_p4 & ap_const_lv1_1);
    tmp_9_fu_935_p3 <= (p_Result_25_fu_925_p4 & ap_const_lv1_1);
    tmp_fu_222_p4 <= x_int_reg(31 downto 30);
    tmp_s_fu_1017_p3 <= (p_Result_28_fu_1007_p4 & ap_const_lv1_1);
    x_l_I_V_31_fu_262_p3 <= 
        zext_ln666_fu_248_p1 when (icmp_ln443_reg_1529(0) = '1') else 
        p_Result_50_fu_251_p5;
    x_l_I_V_32_fu_342_p3 <= 
        x_l_I_V_31_fu_262_p3 when (icmp_ln443_1_fu_308_p2(0) = '1') else 
        p_Result_52_fu_320_p5;
    x_l_I_V_33_fu_424_p3 <= 
        x_l_I_V_32_fu_342_p3 when (icmp_ln443_2_fu_390_p2(0) = '1') else 
        p_Result_55_fu_402_p5;
    x_l_I_V_34_fu_506_p3 <= 
        x_l_I_V_33_fu_424_p3 when (icmp_ln443_3_fu_472_p2(0) = '1') else 
        p_Result_58_fu_484_p5;
    x_l_I_V_35_fu_588_p3 <= 
        x_l_I_V_34_fu_506_p3 when (icmp_ln443_4_fu_554_p2(0) = '1') else 
        p_Result_61_fu_566_p5;
    x_l_I_V_36_fu_670_p3 <= 
        x_l_I_V_35_fu_588_p3 when (icmp_ln443_5_fu_636_p2(0) = '1') else 
        p_Result_64_fu_648_p5;
    x_l_I_V_37_fu_827_p3 <= 
        x_l_I_V_fu_749_p3 when (icmp_ln443_7_fu_793_p2(0) = '1') else 
        p_Result_70_fu_805_p5;
    x_l_I_V_38_fu_909_p3 <= 
        x_l_I_V_37_fu_827_p3 when (icmp_ln443_8_fu_875_p2(0) = '1') else 
        p_Result_73_fu_887_p5;
    x_l_I_V_39_fu_991_p3 <= 
        x_l_I_V_38_fu_909_p3 when (icmp_ln443_9_fu_957_p2(0) = '1') else 
        p_Result_76_fu_969_p5;
    x_l_I_V_40_fu_1073_p3 <= 
        x_l_I_V_39_fu_991_p3 when (icmp_ln443_10_fu_1039_p2(0) = '1') else 
        p_Result_79_fu_1051_p5;
    x_l_I_V_41_fu_1155_p3 <= 
        x_l_I_V_40_fu_1073_p3 when (icmp_ln443_11_fu_1121_p2(0) = '1') else 
        p_Result_82_fu_1133_p5;
    x_l_I_V_42_fu_1239_p3 <= 
        x_l_I_V_41_reg_1563 when (icmp_ln443_12_fu_1209_p2(0) = '1') else 
        p_Result_85_fu_1219_p5;
    x_l_I_V_43_fu_1319_p3 <= 
        x_l_I_V_42_fu_1239_p3 when (icmp_ln443_13_fu_1285_p2(0) = '1') else 
        p_Result_88_fu_1297_p5;
    x_l_I_V_44_fu_1401_p3 <= 
        x_l_I_V_43_fu_1319_p3 when (icmp_ln443_14_fu_1367_p2(0) = '1') else 
        p_Result_91_fu_1379_p5;
    x_l_I_V_45_fu_1467_p3 <= 
        x_l_I_V_44_fu_1401_p3 when (icmp_ln443_15_fu_1433_p2(0) = '1') else 
        p_Result_94_fu_1445_p5;
    x_l_I_V_fu_749_p3 <= 
        x_l_I_V_36_reg_1540 when (icmp_ln443_6_reg_1552(0) = '1') else 
        p_Result_67_fu_730_p5;
    zext_ln212_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_222_p4),3));
    zext_ln443_10_fu_1117_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_1099_p3),14));
    zext_ln443_11_fu_1205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_1198_p3),15));
    zext_ln443_12_fu_1281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_1263_p3),16));
    zext_ln443_13_fu_1363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_1345_p3),17));
    zext_ln443_14_fu_1429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_1417_p3),18));
    zext_ln443_1_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_368_p3),5));
    zext_ln443_2_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_450_p3),6));
    zext_ln443_3_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_532_p3),7));
    zext_ln443_4_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_614_p3),8));
    zext_ln443_5_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_696_p3),9));
    zext_ln443_6_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_771_p3),10));
    zext_ln443_7_fu_871_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_853_p3),11));
    zext_ln443_8_fu_953_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_935_p3),12));
    zext_ln443_9_fu_1035_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_1017_p3),13));
    zext_ln443_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_286_p3),4));
    zext_ln666_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_read_reg_1523),35));
    zext_ln671_fu_1491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_I_V_fu_1483_p3),35));
end behav;
